// Generated by gencpp from file exercise1/sum_of_arrayResponse.msg
// DO NOT EDIT!


#ifndef EXERCISE1_MESSAGE_SUM_OF_ARRAYRESPONSE_H
#define EXERCISE1_MESSAGE_SUM_OF_ARRAYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise1
{
template <class ContainerAllocator>
struct sum_of_arrayResponse_
{
  typedef sum_of_arrayResponse_<ContainerAllocator> Type;

  sum_of_arrayResponse_()
    : result(0)  {
    }
  sum_of_arrayResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sum_of_arrayResponse_

typedef ::exercise1::sum_of_arrayResponse_<std::allocator<void> > sum_of_arrayResponse;

typedef boost::shared_ptr< ::exercise1::sum_of_arrayResponse > sum_of_arrayResponsePtr;
typedef boost::shared_ptr< ::exercise1::sum_of_arrayResponse const> sum_of_arrayResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise1::sum_of_arrayResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercise1::sum_of_arrayResponse_<ContainerAllocator1> & lhs, const ::exercise1::sum_of_arrayResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercise1::sum_of_arrayResponse_<ContainerAllocator1> & lhs, const ::exercise1::sum_of_arrayResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercise1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::exercise1::sum_of_arrayResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise1/sum_of_arrayResponse";
  }

  static const char* value(const ::exercise1::sum_of_arrayResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"\n"
"\n"
;
  }

  static const char* value(const ::exercise1::sum_of_arrayResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sum_of_arrayResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise1::sum_of_arrayResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise1::sum_of_arrayResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE1_MESSAGE_SUM_OF_ARRAYRESPONSE_H
