// Generated by gencpp from file exercise1/sum_of_array.msg
// DO NOT EDIT!


#ifndef EXERCISE1_MESSAGE_SUM_OF_ARRAY_H
#define EXERCISE1_MESSAGE_SUM_OF_ARRAY_H

#include <ros/service_traits.h>


#include <exercise1/sum_of_arrayRequest.h>
#include <exercise1/sum_of_arrayResponse.h>


namespace exercise1
{

struct sum_of_array
{

typedef sum_of_arrayRequest Request;
typedef sum_of_arrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sum_of_array
} // namespace exercise1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exercise1::sum_of_array > {
  static const char* value()
  {
    return "65f9c89928d29d739491ad72c448ad4f";
  }

  static const char* value(const ::exercise1::sum_of_array&) { return value(); }
};

template<>
struct DataType< ::exercise1::sum_of_array > {
  static const char* value()
  {
    return "exercise1/sum_of_array";
  }

  static const char* value(const ::exercise1::sum_of_array&) { return value(); }
};


// service_traits::MD5Sum< ::exercise1::sum_of_arrayRequest> should match
// service_traits::MD5Sum< ::exercise1::sum_of_array >
template<>
struct MD5Sum< ::exercise1::sum_of_arrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exercise1::sum_of_array >::value();
  }
  static const char* value(const ::exercise1::sum_of_arrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise1::sum_of_arrayRequest> should match
// service_traits::DataType< ::exercise1::sum_of_array >
template<>
struct DataType< ::exercise1::sum_of_arrayRequest>
{
  static const char* value()
  {
    return DataType< ::exercise1::sum_of_array >::value();
  }
  static const char* value(const ::exercise1::sum_of_arrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exercise1::sum_of_arrayResponse> should match
// service_traits::MD5Sum< ::exercise1::sum_of_array >
template<>
struct MD5Sum< ::exercise1::sum_of_arrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exercise1::sum_of_array >::value();
  }
  static const char* value(const ::exercise1::sum_of_arrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise1::sum_of_arrayResponse> should match
// service_traits::DataType< ::exercise1::sum_of_array >
template<>
struct DataType< ::exercise1::sum_of_arrayResponse>
{
  static const char* value()
  {
    return DataType< ::exercise1::sum_of_array >::value();
  }
  static const char* value(const ::exercise1::sum_of_arrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXERCISE1_MESSAGE_SUM_OF_ARRAY_H
