// Generated by gencpp from file exercise1/SumOfArray.msg
// DO NOT EDIT!


#ifndef EXERCISE1_MESSAGE_SUMOFARRAY_H
#define EXERCISE1_MESSAGE_SUMOFARRAY_H

#include <ros/service_traits.h>


#include <exercise1/SumOfArrayRequest.h>
#include <exercise1/SumOfArrayResponse.h>


namespace exercise1
{

struct SumOfArray
{

typedef SumOfArrayRequest Request;
typedef SumOfArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SumOfArray
} // namespace exercise1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exercise1::SumOfArray > {
  static const char* value()
  {
    return "65f9c89928d29d739491ad72c448ad4f";
  }

  static const char* value(const ::exercise1::SumOfArray&) { return value(); }
};

template<>
struct DataType< ::exercise1::SumOfArray > {
  static const char* value()
  {
    return "exercise1/SumOfArray";
  }

  static const char* value(const ::exercise1::SumOfArray&) { return value(); }
};


// service_traits::MD5Sum< ::exercise1::SumOfArrayRequest> should match
// service_traits::MD5Sum< ::exercise1::SumOfArray >
template<>
struct MD5Sum< ::exercise1::SumOfArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exercise1::SumOfArray >::value();
  }
  static const char* value(const ::exercise1::SumOfArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise1::SumOfArrayRequest> should match
// service_traits::DataType< ::exercise1::SumOfArray >
template<>
struct DataType< ::exercise1::SumOfArrayRequest>
{
  static const char* value()
  {
    return DataType< ::exercise1::SumOfArray >::value();
  }
  static const char* value(const ::exercise1::SumOfArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exercise1::SumOfArrayResponse> should match
// service_traits::MD5Sum< ::exercise1::SumOfArray >
template<>
struct MD5Sum< ::exercise1::SumOfArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exercise1::SumOfArray >::value();
  }
  static const char* value(const ::exercise1::SumOfArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise1::SumOfArrayResponse> should match
// service_traits::DataType< ::exercise1::SumOfArray >
template<>
struct DataType< ::exercise1::SumOfArrayResponse>
{
  static const char* value()
  {
    return DataType< ::exercise1::SumOfArray >::value();
  }
  static const char* value(const ::exercise1::SumOfArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXERCISE1_MESSAGE_SUMOFARRAY_H
