(cl:defpackage exercise1-srv
  (:use )
  (:export
   "REVERSE"
   "<REVERSE-REQUEST>"
   "REVERSE-REQUEST"
   "<REVERSE-RESPONSE>"
   "REVERSE-RESPONSE"
   "SUMOFARRAY"
   "<SUMOFARRAY-REQUEST>"
   "SUMOFARRAY-REQUEST"
   "<SUMOFARRAY-RESPONSE>"
   "SUMOFARRAY-RESPONSE"
  ))

