// Generated by gencpp from file task2/Cylinder.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_CYLINDER_H
#define TASK2_MESSAGE_CYLINDER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/ColorRGBA.h>
#include <geometry_msgs/PointStamped.h>

namespace task2
{
template <class ContainerAllocator>
struct Cylinder_
{
  typedef Cylinder_<ContainerAllocator> Type;

  Cylinder_()
    : color()
    , point()  {
    }
  Cylinder_(const ContainerAllocator& _alloc)
    : color(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _color_type;
  _color_type color;

   typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::task2::Cylinder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task2::Cylinder_<ContainerAllocator> const> ConstPtr;

}; // struct Cylinder_

typedef ::task2::Cylinder_<std::allocator<void> > Cylinder;

typedef boost::shared_ptr< ::task2::Cylinder > CylinderPtr;
typedef boost::shared_ptr< ::task2::Cylinder const> CylinderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task2::Cylinder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task2::Cylinder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task2::Cylinder_<ContainerAllocator1> & lhs, const ::task2::Cylinder_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task2::Cylinder_<ContainerAllocator1> & lhs, const ::task2::Cylinder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task2::Cylinder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task2::Cylinder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task2::Cylinder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task2::Cylinder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::Cylinder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::Cylinder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task2::Cylinder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e8ee3f2491ff8e55c488b333304dab7";
  }

  static const char* value(const ::task2::Cylinder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e8ee3f2491ff8e5ULL;
  static const uint64_t static_value2 = 0x5c488b333304dab7ULL;
};

template<class ContainerAllocator>
struct DataType< ::task2::Cylinder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task2/Cylinder";
  }

  static const char* value(const ::task2::Cylinder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task2::Cylinder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/ColorRGBA color\n"
"geometry_msgs/PointStamped point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/ColorRGBA\n"
"float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::task2::Cylinder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task2::Cylinder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cylinder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task2::Cylinder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task2::Cylinder_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK2_MESSAGE_CYLINDER_H
