// Generated by gencpp from file task3/Cylinder.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_CYLINDER_H
#define TASK3_MESSAGE_CYLINDER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>

namespace task3
{
template <class ContainerAllocator>
struct Cylinder_
{
  typedef Cylinder_<ContainerAllocator> Type;

  Cylinder_()
    : color()
    , position()  {
    }
  Cylinder_(const ContainerAllocator& _alloc)
    : color(_alloc)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _color_type;
  _color_type color;

   typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::task3::Cylinder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task3::Cylinder_<ContainerAllocator> const> ConstPtr;

}; // struct Cylinder_

typedef ::task3::Cylinder_<std::allocator<void> > Cylinder;

typedef boost::shared_ptr< ::task3::Cylinder > CylinderPtr;
typedef boost::shared_ptr< ::task3::Cylinder const> CylinderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task3::Cylinder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task3::Cylinder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task3::Cylinder_<ContainerAllocator1> & lhs, const ::task3::Cylinder_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task3::Cylinder_<ContainerAllocator1> & lhs, const ::task3::Cylinder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task3::Cylinder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task3::Cylinder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3::Cylinder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3::Cylinder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3::Cylinder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3::Cylinder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task3::Cylinder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79e9171f8aab1d9f862baaaf0114ad4a";
  }

  static const char* value(const ::task3::Cylinder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79e9171f8aab1d9fULL;
  static const uint64_t static_value2 = 0x862baaaf0114ad4aULL;
};

template<class ContainerAllocator>
struct DataType< ::task3::Cylinder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task3/Cylinder";
  }

  static const char* value(const ::task3::Cylinder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task3::Cylinder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color\n"
"geometry_msgs/PointStamped position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::task3::Cylinder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task3::Cylinder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cylinder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task3::Cylinder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task3::Cylinder_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.color);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK3_MESSAGE_CYLINDER_H
