// Generated by gencpp from file task3/FacePose.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_FACEPOSE_H
#define TASK3_MESSAGE_FACEPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace task3
{
template <class ContainerAllocator>
struct FacePose_
{
  typedef FacePose_<ContainerAllocator> Type;

  FacePose_()
    : position()  {
    }
  FacePose_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::task3::FacePose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task3::FacePose_<ContainerAllocator> const> ConstPtr;

}; // struct FacePose_

typedef ::task3::FacePose_<std::allocator<void> > FacePose;

typedef boost::shared_ptr< ::task3::FacePose > FacePosePtr;
typedef boost::shared_ptr< ::task3::FacePose const> FacePoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task3::FacePose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task3::FacePose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task3::FacePose_<ContainerAllocator1> & lhs, const ::task3::FacePose_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task3::FacePose_<ContainerAllocator1> & lhs, const ::task3::FacePose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task3::FacePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task3::FacePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3::FacePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3::FacePose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3::FacePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3::FacePose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task3::FacePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80642f0dbeee9f13de99f968daa46e52";
  }

  static const char* value(const ::task3::FacePose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80642f0dbeee9f13ULL;
  static const uint64_t static_value2 = 0xde99f968daa46e52ULL;
};

template<class ContainerAllocator>
struct DataType< ::task3::FacePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task3/FacePose";
  }

  static const char* value(const ::task3::FacePose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task3::FacePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::task3::FacePose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task3::FacePose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FacePose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task3::FacePose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task3::FacePose_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK3_MESSAGE_FACEPOSE_H
