// Generated by gencpp from file exercise2/Movement.msg
// DO NOT EDIT!


#ifndef EXERCISE2_MESSAGE_MOVEMENT_H
#define EXERCISE2_MESSAGE_MOVEMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise2
{
template <class ContainerAllocator>
struct Movement_
{
  typedef Movement_<ContainerAllocator> Type;

  Movement_()
    {
    }
  Movement_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::exercise2::Movement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise2::Movement_<ContainerAllocator> const> ConstPtr;

}; // struct Movement_

typedef ::exercise2::Movement_<std::allocator<void> > Movement;

typedef boost::shared_ptr< ::exercise2::Movement > MovementPtr;
typedef boost::shared_ptr< ::exercise2::Movement const> MovementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise2::Movement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise2::Movement_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace exercise2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exercise2::Movement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise2::Movement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise2::Movement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise2::Movement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise2::Movement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise2::Movement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise2::Movement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::exercise2::Movement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise2::Movement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise2/Movement";
  }

  static const char* value(const ::exercise2::Movement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise2::Movement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::exercise2::Movement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise2::Movement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Movement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise2::Movement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::exercise2::Movement_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE2_MESSAGE_MOVEMENT_H
