// Generated by gencpp from file exercise2/MovementType.msg
// DO NOT EDIT!


#ifndef EXERCISE2_MESSAGE_MOVEMENTTYPE_H
#define EXERCISE2_MESSAGE_MOVEMENTTYPE_H

#include <ros/service_traits.h>


#include <exercise2/MovementTypeRequest.h>
#include <exercise2/MovementTypeResponse.h>


namespace exercise2
{

struct MovementType
{

typedef MovementTypeRequest Request;
typedef MovementTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovementType
} // namespace exercise2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exercise2::MovementType > {
  static const char* value()
  {
    return "f747a6d49b629ea3b92ea322ab71d841";
  }

  static const char* value(const ::exercise2::MovementType&) { return value(); }
};

template<>
struct DataType< ::exercise2::MovementType > {
  static const char* value()
  {
    return "exercise2/MovementType";
  }

  static const char* value(const ::exercise2::MovementType&) { return value(); }
};


// service_traits::MD5Sum< ::exercise2::MovementTypeRequest> should match
// service_traits::MD5Sum< ::exercise2::MovementType >
template<>
struct MD5Sum< ::exercise2::MovementTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exercise2::MovementType >::value();
  }
  static const char* value(const ::exercise2::MovementTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise2::MovementTypeRequest> should match
// service_traits::DataType< ::exercise2::MovementType >
template<>
struct DataType< ::exercise2::MovementTypeRequest>
{
  static const char* value()
  {
    return DataType< ::exercise2::MovementType >::value();
  }
  static const char* value(const ::exercise2::MovementTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exercise2::MovementTypeResponse> should match
// service_traits::MD5Sum< ::exercise2::MovementType >
template<>
struct MD5Sum< ::exercise2::MovementTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exercise2::MovementType >::value();
  }
  static const char* value(const ::exercise2::MovementTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise2::MovementTypeResponse> should match
// service_traits::DataType< ::exercise2::MovementType >
template<>
struct DataType< ::exercise2::MovementTypeResponse>
{
  static const char* value()
  {
    return DataType< ::exercise2::MovementType >::value();
  }
  static const char* value(const ::exercise2::MovementTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXERCISE2_MESSAGE_MOVEMENTTYPE_H
